### PR TITLE
AMD Hip implementation

### PR DESCRIPTION
**Pull request by ritrac**
This patch adds the support for AMD GPUs. It's based on the CUDA implementation and runs on CDNA2 and RDNA3 (Rhel9.4 and rocm6.1.3). It's related to issue #51 

The build option "FIRESTARTER_HIP" is added to build the binary "src/FIRESTARTER_HIP". 
It depends on hipblas and  rocrand. 

I chose to duplicate "cuda.cpp" because it's not a 1 to 1 translation and to simplify the validation.  Besides the renaming of the calls cuda*  to hip*, the major changes are:

- renaming of the overloaded functions "cuda_safe_call" since hipError_t, hipblasStatus_t and  hiprandStatus_t are of the same type. 
- migration from rocContext to HipStream (CTX are deprecated),  parallel GPUs is validated.

### CODE REVIEW

**Comment by rschoene** [comment]
Thank you for your submission, I have some time reserved for FIRESTARTER this month and will then look into it.

**Comment by rschoene** [comment]
Small update: Unfortunately, the AMD nodes have been in maintenance during the whole week. I hope they'll be available tomorrow.

**Comment by rschoene** [comment]
I started merging it and try to integrate it in the existing Cuda.cpp to avoid duplicate code. You can follow the progress in the merge-amdgpu branch

**Comment by rschoene** [comment]
The branch is now building in the pipeline. Would you mind testing it?

**Comment by ritrac** [comment]
It's working fine too on an mi300x node with the latest rocm (6.2).
I have not seen any stability issue and the full TDP is achieved (8x 750W). 

Thanks

**Comment by rschoene** [comment]
The other branch was now merged

**Pull request closed without merging**
