### PR TITLE
Caliper

### PR DESCRIPTION
**Pull request by tjeter**
I have added Caliper annotations to Firestarter in various regions. Some annotations have commented out because they do not yield significant results reported in the call tree of a Caliper file.

### CODE REVIEW

**Comment by rschoene** [comment]
This will not be merged for two main reasons. Please read to the end if you want to include Caliper in the future.

# Reason 1: Clean code:

There are multiple lines which are just commented out. This should not be the case.

# Reason 2: We already have too many dependencies

I would rather not add another dependency to the main code but have an optional dependency where you can link things to FS, if you want to. We already have VT and Score-P instrumentation, which could have been used as a hook to match against Caliper. I also worry about the possible testing of the frameworks.

# How to proceed and get Caliper into FS?
Please have a look at this new issue #55 . I think the code would be cleaner if there were not too many includes and ifdefs spread over all of the code but have it separated away. Maybe you could help with that?

Once this is done, you can add a new pull request

Best regards

**Comment by rschoene** [comment]
Please have a look at: https://github.com/tud-zih-energy/FIRESTARTER/tree/unifytracing for a first draft.

**Comment by rschoene** [comment]
@tjeter any comments or suggestions?

**Comment by tjeter** [comment]
@rschoene I am taking a look at this. I will try to have a PR soon.

**Comment by rschoene** [comment]
@tjeter great to hear. please have a look at the updates :) It should make things easier...

**Comment by rschoene** [comment]
@tjeter I would merge the https://github.com/tud-zih-energy/FIRESTARTER/tree/marenz.unify_tracing soon. Do you have any additions that are missing?

**Comment by rschoene** [comment]
(with soon, I'd mean June 2025)

**Pull request closed without merging**
